### ISSUE TITLE
Error: Nest can't resolve dependencies of the APP_INTERCEPTOR

### ISSUE THREAD

**Issue by omidh28** [acal11/nestjs-rate-limit#59]
When using global Interceptor/guard it throws this error even though Rate Limiter module is imported:

`Error: Nest can't resolve dependencies of the APP_INTERCEPTOR`

I'm using version 1.0.7

**Comment by acal11** [comment]
I am able to use the package without any errors, so it could potentially be a consumption issue. Please have a look at [this StackOverflow question](https://stackoverflow.com/questions/58436589/nestjs-global-cache-cacheinterceptor-problem) and see if it helps.

**Comment by omidh28** [comment]
Can you share an example repo? I tried creating a new nest app but It didn't work either

**Comment by acal11** [comment]
https://github.com/acal11/nestjs-rate-limit/tree/master/example-project

**Comment by acal11** [comment]
Is this issue resolved now?

**Comment by omidh28** [comment]
I'll test it soon

**Comment by omidh28** [comment]
@acal11  Well, Docs never mentioned to call `forRoot` and I just imported the module itself.
